spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:bankingdb
        username: sa
        password: password
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger
