spring:
    datasource:
        password: 123456
        testWhileIdle: true
        url: jdbc:mysql://localhost:3306/banking_api?useTimezone=true&serverTimezone=America/Sao_Paulo&createDatabaseIfNotExist=true
        username: root
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger
